# Site settings
title: Bernard Kowalski
author: Bernard Kowalski
email: hi@bernk.com
description: > # The personal website of Bernard Kowalski, the UI designer and front-end developer, not the Hollywood film director.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bernk.com" # the base hostname & protocol for your site
twitter_username: bernk
github_username:  bernk

# Build settings
markdown: kramdown
